server:
  port: 88
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
rest:
  auth-open: true
  sign-open: true
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  session:
    store-type: none
  multipart:
    maxFileSize: 10Mb
    maxRequestSize: 10Mb
  activiti:
    ####校验流程文件，默认校验resources下的processes文件夹里的流程文件  
    check-process-definitions: false
  redis:
    database: 0
    host: 111.231.225.233
    port: 6699
    password: jeebase
    timeout: 6000
    pool:
       #max-active: 1000
      #max-wait: -1
      max-idle: 10
      min-idle: 5
  data:
    elasticsearch:
      #cluster-name: #默认为elasticsearch
      #cluster-nodes: 127.0.0.1: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    request-context-attribute: request
    suffix: .html
    template-loader-path: /WEB-INF/
    settings:
      auto_import: /common/ftl/index.ftl as p,/common/ftl/spring.ftl as s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.225.233:5186/jeecloud?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: jeebase
    password: 1qaz2wsx3edc
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filter:
      stat:
        log-slow-sql: true
  aop:
    proxy-target-class: true
mybatis:
  type-aliases-package: com.mostch.common.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    cache-enabled: true
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:log4j2.xml
  path: /logs/jeecloud
  level:
    com.jeecloud: DEBUG
dream:
  weixin:
    dev-mode: true
    wx-configs:
      - appId: wx9803d1188fa5fbda
        appSecret: db859c968763c582794e7c3d003c3d87
      - appId: wxc03edcd008ad1e70
        appSecret: 11ed9e2b8e3e3c131e7be320a42b2b5a
        token: 123456
    wxa-config:
      appid: wx4f53594f9a6b3dcb
      appSecret: eec6482ba3804df05bd10895bace0579
flowable:
  check-process-definitions: false